In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import os

project_path = "/content/drive/MyDrive/Fraud Detection"

os.makedirs(project_path, exist_ok=True)

print("Project folder ready at:", project_path)

Project folder ready at: /content/drive/MyDrive/Fraud Detection

In [12]:
# Import libraries for model testing
import pandas as pd
import pickle
import tensorflow as tf
from sklearn.metrics import classification_report

In [15]:
# Load model
model = tf.keras.models.load_model(
"/content/drive/MyDrive/Fraud Detection/models/fraud_nn_smote_v1.h5"
)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [16]:
# Load scaler
with open("/content/drive/MyDrive/Fraud Detection/models/scaler_smote_v1.pkl","rb") as f:
    scaler = pickle.load(f)

In [18]:
# Load new transactions
df = pd.read_csv("/content/drive/MyDrive/Fraud_Detection_Project/creditcard_2023.csv")
df.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0

In [22]:
X = df.drop(['Class', 'id'], axis=1)
y = df['Class']

In [23]:
df.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0

In [24]:
# Scale
X_scaled = scaler.transform(X)

In [25]:
# Predict
y_pred_prob = model.predict(X_scaled)
y_pred = (y_pred_prob > 0.5).astype(int)

print(classification_report(y, y_pred))

17770/17770 ━━━━━━━━━━━━━━━━━━━━ 27s 2ms/step
              precision    recall  f1-score   support

           0       0.50      1.00      0.67    284315
           1       1.00      0.00      0.01    284315

    accuracy                           0.50    568630
   macro avg       0.75      0.50      0.34    568630
weighted avg       0.75      0.50      0.34    568630

In [26]:
print(df['Class'].value_counts())

Class
0    284315
1    284315
Name: count, dtype: int64